workflows:
  android-workflow:
    name: Build Android AAB
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Generate Hive adapters
        script: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android App Bundle (Debug)
        script: |
          flutter build appbundle --debug

    artifacts:
      - build/app/outputs/bundle/debug/app-debug.aab

    publishing:
      email:
        recipients:
          - 643905958@qq.com  # ← 改成你的邮箱
