workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: none  # 仍建议保留
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          
  - name: Generate Hive adapters (build_runner)
    script: |
      flutter pub run build_runner build --delete-conflicting-outputs

  - name: Get dependencies
    script: flutter pub get

  - name: Generate Hive code
    script: |
      flutter pub run build_runner build --delete-conflicting-outputs

  - name: Build app bundle
    script: |
      flutter build appbundle --debug
  - name: Get dependencies
    script: flutter pub get

  - name: Generate Hive adapters
    script: |
      flutter pub run build_runner build --delete-conflicting-outputs

  - name: Build app bundle
    script: flutter build appbundle --debug
          
  - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - 643905958@qq.com
