workflows:
  android-apk:
    name: Build Android APK
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: none  # 仍建议保留
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - 643905958@qq.com
